;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-regexp
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-star
        comment-or-uncomment-region-or-line
        crux-move-beginning-of-line
        easy-kill
        haskell-indentation-common-electric-command
        indent-for-tab-command
        markdown-exdent-or-delete
        org-delete-char
        org-end-of-line
        org-self-insert-command
        select-window-2
        sp-backward-delete-char
        sp-delete-char
        upcase-region
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        crux-view-url
        handle-switch-frame
        mc/mark-next-lines
        select-window-6
        smex
        undo-tree-visualize
        yaml-electric-dash-and-dot
        ))
