(prelude-require-package 'multiple-cursors)
(prelude-require-package 'neotree)
(prelude-require-package 'window-numbering)
(prelude-require-package 'string-inflection)
(prelude-require-package 'rg)
(prelude-require-package 'haskell-mode)
(prelude-require-package 'erlang)
(prelude-require-package 'ruby-tools)
(prelude-require-package 'command-log-mode)
(prelude-require-package 'ivy-rich)
(prelude-require-package 'windresize)
(prelude-require-package 'ztree)
(prelude-require-package 'shell-pop)
(prelude-require-package 'ruby-compilation)
(prelude-require-package 'ivy-searcher)

;; Look into this (Emacs from scratch #2 - Adding UI Improvements 36:00 ish) - Casey, Tue Oct 04 2022
;; (prelude-require-package 'helpful)

;; (prelude-require-package 'terminal-toggle)
;; '(terminal-toggle--term-shell "/bin/bash")
;; (prelude-require-package 'multi-term)
