#+title: Emacs Config

* DISABLED Package Management

** Use Package

Install packages by default when configured with use-package.

NOTE: I'm going to try not using this for now, but storing it here for later as
it will probably make the file cleaner in the long run

#+begin_src emacs-lisp :tangle no
(setq use-package-always-ensure t)
#+end_src

Macro to use to configure built-in features, rather than packages that do not
need to be installed.

#+begin_src emacs-lisp :tangle no
(defmacro use-feature (name &rest args)
  "`use-package' with package installation (`ensure') disabled."
  (declare (indent defun))
  `(use-package ,name
     :ensure nil
     ,@args))
#+end_src

* Base Settings

** Customization Saving

Do not save customizations in =init.el=, instead save them in a temporary file
that will be discarded. As a result, any customizations made in a session will
not be persisted across sessions.

The reason for not using customizations is to force the use and understanding of
configuring Emacs myself, rather than relying on a UI. This will give me
confidence in full control of Emacs and how to properly do that.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name
                   (format "custom-%d-%d.el" (emacs-pid) (random))
                   temporary-file-directory))
#+end_src

** No Littering

Move all common files typically written to the =user-emacs-directory= to the =var=
and =etc= subdirectories so that they can be included in =.gitignore=

This was also highly recommended by =emacs from scratch= as it keeps your
directory cleaner

#+begin_src emacs-lisp
(use-package no-littering
  :ensure (:wait t))
#+end_src

** Minibuffer

Support opening new minibuffers from inside existing minibuffers.

NOTE: Not sure if I'll like this, disabling for now

#+begin_src emacs-lisp :tangle no
(setq enable-recursive-minibuffers t)
#+end_src

Do not allow the cursor in the minibuffer prompt.

#+begin_src emacs-lisp
(setq minibuffer-prompt-properties
      '(read-only t cursor-intangible t face minibuffer-prompt))

(add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
#+end_src

** Save History

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp
(use-package savehist
  :init
  (savehist-mode))
#+end_src

* Assistance

** Which Key

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp
(use-package which-key
  :init
  (which-key-mode))
#+end_src

** Helpful

#+begin_src emacs-lisp
(use-package helpful
  :ensure t
  :bind (
         ;; Remap standard commands
         ([remap describe-function] . #'helpful-callable)
         ([remap describe-command] . #'helpful-command)
         ([remap describe-variable] . #'helpful-variable)
         ([remap describe-symbol] . #'helpful-symbol)
         ([remap describe-key] . #'helpful-key)))
#+end_src

* User Interface

** Font Size

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp
(use-package emacs
  :bind (("s-=" . #'global-text-scale-adjust)
         ("s--" . #'global-text-scale-adjust)
         ("s-0" . #'global-text-scale-adjust)
         ("C-=" . #'text-scale-adjust)
         ("C--" . #'text-scale-adjust)
         ("C-0" . #'text-scale-adjust))

  :preface
  (defvar presentation-mode-font-size 21)
  (defvar presentation-mode-enabled nil)
  (defun presentation-mode ()
    "Increase the font size for presentation."
    (interactive)
    ;; Is there a better way to toggle? Maybe this should actually be a "mode".
    ;; Added due to the comment below about the old if condition taking the
    ;; current font size and dividing by 10 and it not matching the original
    ;; size set - Casey, Sat Nov 23 2024
    (setq presentation-mode-enabled (not presentation-mode-enabled))

    (let* ((current-font-size (/ (face-attribute 'default :height) 10))
           (new-font-size
            ;; Previously this was `(if (not (eq current-font-size
            ;; presentation-mode-font-size))` but for some reason after
            ;; assigning the font to 15 it was comming back as 14 (148 / 10),
            ;; changed to be a boolean until I can learn how to create a mode
            ;; properly - Casey, Sat Nov 23 2024
            (if presentation-mode-enabled
                presentation-mode-font-size
              custom/monospace-font-size)))
      (set-face-attribute 'default nil :height (* new-font-size 10))
      (set-face-attribute 'variable-pitch nil :height (* new-font-size 10))
      (redisplay 'force))))
#+end_src

** Completion Menu (Vertico)

#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :init
  (vertico-mode))
#+end_src

** Consult

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :bind (("C-x b" . consult-buffer)))
#+end_src

** Completion Style (Orderless)

The orderless completion style allows typing parts of what is being matched,
separated by spaces. For example, "som thi" will match "this-is-some-thing".

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

* Projects

** Tree Viewer (Treemacs)

#+begin_src emacs-lisp
(use-package treemacs
  :ensure t
  :bind ("s-b" . #'treemacs)
  :config
  (treemacs-follow-mode))
#+end_src

* Version Control

** Magit

#+begin_src emacs-lisp
(use-package transient
  :ensure t)

(use-package magit
  :ensure t
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

* Startup Time

Aaron had it setup to print out the start up time. I realize now that is a very
important thing to keep an eye on, but I usually leave Emacs open for extended
periods of time and don't close it often. Mostly leaving this a reminder to be
efficient in my configuration and always consider trade offs and decisions
rather than blowing past them.

Changed this from using a web hook:

#+begin_src emacs-lisp :tangle no
(add-hook 'after-init-hook
          (lambda ()
            (let ((inhibit-message t))
              (message "Emacs init time: %s" (emacs-init-time)))))
#+end_src

to setting the function =startup-echo-area-message= as that is the message that
Emacs will show at the bottom of the screen at startup and the default one is
very difficult to ignore

#+begin_src emacs-lisp
(defun startup-echo-area-message ()
  (format "Emacs init time: %s" (emacs-init-time)))
#+end_src
