#+title: Emacs Config

* Base Settings

** Customization Saving

Do not save customizations in =init.el=, instead save them in a temporary file
that will be discarded. As a result, any customizations made in a session will
not be persisted across sessions.

The reason for not using customizations is to force the use and understanding of
configuring Emacs myself, rather than relying on a UI. This will give me
confidence in full control of Emacs and how to properly do that.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name
                   (format "custom-%d-%d.el" (emacs-pid) (random))
                   temporary-file-directory))
#+end_src

** No Littering

Move all common files typically written to the =user-emacs-directory= to the =var=
and =etc= subdirectories so that they can be included in =.gitignore=

This was also highly recommended by =emacs from scratch= as it keeps your
directory cleaner

#+begin_src emacs-lisp
(use-package no-littering
  :ensure (:wait t))
#+end_src

* Startup Time

Aaron had it setup to print out the start up time. I realize now that is a very
important thing to keep an eye on, but I usually leave Emacs open for extended
periods of time and don't close it often. Mostly leaving this a reminder to be
efficient in my configuration and always consider trade offs and decisions
rather than blowing past them.

Changed this from using a web hook:

#+begin_src emacs-lisp :tangle no
(add-hook 'after-init-hook
          (lambda ()
            (let ((inhibit-message t))
              (message "Emacs init time: %s" (emacs-init-time)))))
#+end_src

to setting the function =startup-echo-area-message= as that is the message that
Emacs will show at the bottom of the screen at startup and the default one is
very difficult to ignore

#+begin_src emacs-lisp
(defun startup-echo-area-message ()
  (format "Emacs init time: %s" (emacs-init-time)))
#+end_src
