#+title: Emacs Config

* DISABLED Package Management

** Use Package

Install packages by default when configured with use-package.

NOTE: I'm going to try not using this for now, but storing it here for later as
it will probably make the file cleaner in the long run

#+begin_src emacs-lisp :tangle no

(setq use-package-always-ensure t)

#+end_src

Macro to use to configure built-in features, rather than packages that do not
need to be installed.

#+begin_src emacs-lisp :tangle no

(defmacro use-feature (name &rest args)
  "`use-package' with package installation (`ensure') disabled."
  (declare (indent defun))
  `(use-package ,name
     :ensure nil
     ,@args))

#+end_src

* Base Settings

** General

Don't worry about lockfiles.

#+begin_src emacs-lisp

(setq create-lockfiles nil)

#+end_src

** Customization Saving

Do not save customizations in =init.el=, instead save them in a temporary file
that will be discarded. As a result, any customizations made in a session will
not be persisted across sessions.

The reason for not using customizations is to force the use and understanding of
configuring Emacs myself, rather than relying on a UI. This will give me
confidence in full control of Emacs and how to properly do that.

#+begin_src emacs-lisp

(setq custom-file (expand-file-name
                   (format "custom-%d-%d.el" (emacs-pid) (random))
                   temporary-file-directory))

#+end_src

** No Littering

Move all common files typically written to the =user-emacs-directory= to the =var=
and =etc= subdirectories so that they can be included in =.gitignore=

This was also highly recommended by =emacs from scratch= as it keeps your
directory cleaner

#+begin_src emacs-lisp

(use-package no-littering
  :ensure (:wait t)
  :after treesit)

#+end_src

** Minibuffer

Support opening new minibuffers from inside existing minibuffers.

NOTE: Not sure if I'll like this, disabling for now

#+begin_src emacs-lisp :tangle no

(setq enable-recursive-minibuffers t)

#+end_src

Do not allow the cursor in the minibuffer prompt.

#+begin_src emacs-lisp

(setq minibuffer-prompt-properties
      '(read-only t cursor-intangible t face minibuffer-prompt))

(add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

#+end_src

** Save History

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package savehist
  :init
  (savehist-mode))

#+end_src

** Backup and Auto-Save

Put backup files and auto-save files in var directory, rather than alongside the
original files.

#+begin_src emacs-lisp

(setq backup-directory-alist `(("." . ,(no-littering-expand-var-file-name "backup/"))))

(add-hook 'elpaca-after-init-hook
          (lambda ()
            (setq auto-save-list-file-prefix (no-littering-expand-var-file-name "auto-save/sessions/")
                  auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))))

#+end_src

When paths are too long, there can be errors when auto-save and backup filenames
are generated. This uses a consistent hash, rather than the full path to
generate the filenames. This is taken from Doom Emacs.

#+begin_src emacs-lisp

(defun custom/make-auto-save-file-name-hashed (fn)
  "Compress the auto-save file name so paths don't get too long."
  (let ((buffer-file-name
         (if (or (null buffer-file-name)
                 (find-file-name-handler buffer-file-name 'make-auto-save-file-name))
             buffer-file-name
           (sha1 buffer-file-name))))
    (funcall fn)))
(advice-add #'make-auto-save-file-name :around #'custom/make-auto-save-file-name-hashed)

(defun custom/make-backup-file-name-hashed (fn file)
  "A few places use the backup file name so paths don't get too long."
  (let ((alist backup-directory-alist)
        backup-directory)
    (while alist
      (let ((elt (car alist)))
        (if (string-match (car elt) file)
            (setq backup-directory (cdr elt) alist nil)
          (setq alist (cdr alist)))))
    (let ((file (funcall fn file)))
      (if (or (null backup-directory)
              (not (file-name-absolute-p backup-directory)))
          file
        (expand-file-name (sha1 (file-name-nondirectory file))
                          (file-name-directory file))))))
(advice-add #'make-backup-file-name-1 :around #'custom/make-backup-file-name-hashed)

#+end_src

* Assistance

** Which Key

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package which-key
  :init
  (which-key-mode))

#+end_src

** Helpful

#+begin_src emacs-lisp

(use-package helpful
  :ensure t
  :bind (
         ;; Remap standard commands
         ([remap describe-function] . #'helpful-callable)
         ([remap describe-command] . #'helpful-command)
         ([remap describe-variable] . #'helpful-variable)
         ([remap describe-symbol] . #'helpful-symbol)
         ([remap describe-key] . #'helpful-key)))

#+end_src

* User Interface

** Color Theme

Modus themes are great for high contrast for easy visibility

#+begin_src emacs-lisp

  (use-package modus-themes
    :ensure t
    :init (load-theme 'modus-operandi t))

#+end_src

** Window Numbering

#+begin_src emacs-lisp

(use-package window-numbering
  :ensure t
  :config
  (window-numbering-mode 1))

#+end_src

** Font Size

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package emacs
  :bind (("s-=" . #'global-text-scale-adjust)
         ("s--" . #'global-text-scale-adjust)
         ("s-0" . #'global-text-scale-adjust)
         ("C-=" . #'text-scale-adjust)
         ("C--" . #'text-scale-adjust)
         ("C-0" . #'text-scale-adjust))

  :preface
  (defvar presentation-mode-font-size 21)
  (defvar presentation-mode-enabled nil)
  (defun presentation-mode ()
    "Increase the font size for presentation."
    (interactive)
    ;; Is there a better way to toggle? Maybe this should actually be a "mode".
    ;; Added due to the comment below about the old if condition taking the
    ;; current font size and dividing by 10 and it not matching the original
    ;; size set - Casey, Sat Nov 23 2024
    (setq presentation-mode-enabled (not presentation-mode-enabled))

    (let* ((current-font-size (/ (face-attribute 'default :height) 10))
           (new-font-size
            ;; Previously this was `(if (not (eq current-font-size
            ;; presentation-mode-font-size))` but for some reason after
            ;; assigning the font to 15 it was comming back as 14 (148 / 10),
            ;; changed to be a boolean until I can learn how to create a mode
            ;; properly - Casey, Sat Nov 23 2024
            (if presentation-mode-enabled
                presentation-mode-font-size
              custom/monospace-font-size)))
      (set-face-attribute 'default nil :height (* new-font-size 10))
      (set-face-attribute 'variable-pitch nil :height (* new-font-size 10))
      (redisplay 'force))))

#+end_src

** Tab Bar

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package tab-bar
  :bind (("s-t" . #'tab-new)
         ("s-w" . #'tab-close)
         ("s-T" . #'tab-undo))

  :config
  (setq tab-bar-show t
        tab-bar-new-tab-choice t
        tab-bar-new-button nil
        tab-bar-close-button-show nil
        tab-bar-new-tab-to 'rightmost
        ;; If this is the default (t) the name format function below causes
        ;; emacs to hang on boot since commit ca3763af5cc2758ec71700029558e6ecc4379ea9
        tab-bar-auto-width nil))

#+end_src

*** DISABLED Modern Tab Styling

## I want to understand how he did the styling before I use it - Casey, Wed Nov 27 2024

#+begin_src emacs-lisp :tangle no

(use-package modern-tab-bar
  :after tab-bar
  :ensure (modern-tab-bar :host github :repo "aaronjensen/emacs-modern-tab-bar" :protocol ssh)
  :init
  (modern-tab-bar-mode))

#+end_src

** Completion Menu (Vertico)

#+begin_src emacs-lisp

(use-package vertico
  :ensure t
  :init
  (vertico-mode))

#+end_src

** Consult

#+begin_src emacs-lisp

(use-package consult
  :ensure t
  :bind (("C-x b" . consult-buffer)))

#+end_src

** Completion Style (Orderless)

The orderless completion style allows typing parts of what is being matched,
separated by spaces. For example, "som thi" will match "this-is-some-thing".

#+begin_src emacs-lisp

(use-package orderless
  :ensure t
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))

#+end_src

** Completion at Point

*** Completion-at-Point Function Configuration

Add =:capf= and =:compdef= to =use-package=.

#+begin_src emacs-lisp

(use-package compdef
  :ensure (:wait t))

#+end_src

*** Inline Completion (Corfu)

#+begin_src emacs-lisp

(use-package corfu
  :ensure t
  :bind
  (:map corfu-map
        ("TAB" . corfu-next)
        ([tab] . corfu-next)
        ("S-TAB" . corfu-previous)
        ([backtab] . corfu-previous)
        ("C-n" . nil)
        ("C-p" . nil)
        ([remap next-line] . nil)
        ([remap previous-line] . nil)
        ([remap move-end-of-line] . nil)
        ([remap move-beginning-of-line] . nil)
        ("\r" . nil)
        ("<escape>" . corfu-quit))

  :init
  ;; Tab will trigger completion if it does not need to indent
  (setq tab-always-indent 'complete)

  ;; Disable text-mode ispell completion at point function
  (setq text-mode-ispell-word-completion nil)

  ;; TAB-and-Go customizations
  (setq
   ;; Enable cycling for `corfu-next/previous'
   corfu-cycle t
   corfu-preselect 'prompt)

  ;; Auto completion
  (setq
   corfu-auto t
   corfu-auto-prefix 2
   corfu-auto-delay 0.1)

  :config
  (corfu-history-mode))

#+end_src

*** Additional Completion-at-Point Functions (cape)

#+begin_src emacs-lisp

(use-package cape
  :ensure t
  :config
  (setq cape-dabbrev-check-other-buffers nil))

#+end_src

*** DISABLED Ripgrep Completion-at-Point Function

## I want to understand what the package he created does before I use it - Casey, Wed Nov 27 2024

#+begin_src emacs-lisp :tangle no

(use-package ripgrep-capf
  :after cape
  :ensure (:host github :repo "aaronjensen/ripgrep-capf" :protocol ssh)

  :init
  (defalias 'capf-dabbrev-ripgrep (cape-capf-super #'cape-dabbrev #'ripgrep-capf)))

#+end_src

** Acting on Completions (Embark)

#+begin_src emacs-lisp

(use-package embark
  :ensure t
  :bind
  (:map
    vertico-map
    ("C-c C-o" . #'embark-export)
    ("C-c C-c" . #'embark-act)
    ("C-c C-e" . #'custom/embark-export-wgrep))
  :preface
  (defvar custom/embark-export-wgrep nil)
  (defun custom/embark-export-wgrep ()
    "Embark export then wgrep"
    (interactive)
    (setq custom/embark-export-wgrep t)
    (command-execute #'embark-export)))

(use-package embark-consult
  :ensure t
  :config
  (declare-function wgrep-change-to-wgrep-mode "ext:wgrep")

  (defun custom/embark-export-grep-wgrep (&rest _)
    "Start wgrep when indicated"
    (when custom/embark-export-wgrep
      (setq custom/embark-export-wgrep nil)
      (when (eq major-mode 'grep-mode)
        (wgrep-change-to-wgrep-mode))))

  (advice-add #'embark-consult-export-grep :after #'custom/embark-export-grep-wgrep))

#+end_src

** Modeline (doom-modeline)

The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

(use-package all-the-icons
  :ensure t)

(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

#+end_src

* Keybinding Configuration

** Leader key (general)

#+begin_src emacs-lisp

(use-package general
  :ensure t
  :after evil
  :config
  (general-create-definer custom/leader-keys
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "C-SPC")

  (custom/leader-keys
    ":" '(execute-extended-command :which-key "M-x")

    "c" '(:ignore c :which-key "Comment")
    "c a" '(custom/comment-attribution :which-key "Attribute Comment")

    "d" '(custom/insert-date-time :which-key "Insert Current Time")

    "f" '(:ignore f :which-key "File")
    "f s" '(save-buffer :which-key "Save")

    "g" '(:ignore g :which-key "Git")
    "g b" '(magit-blame :which-key "Blame")
    "g g" '(magit :which-key "Status")
    "g L" '(magit-log-buffer-file :which-key "Log file")

    "h" '(:ignore h :which-key "Help")
    "h a" '(apropos :which-key "All")
    "h c" '(describe-command :which-key "Command")
    "h f" '(describe-function :which-key "Function")
    "h k" '(describe-key :which-key "Key")
    "h l" '(view-lossage :which-key "Previous Keys")
    "h s" '(describe-symbol :which-key "Symbol")
    "h v" '(describe-variable :which-key "Variable")

    "p"  '(:ignore p :which-key "Project")

    ;; ## Should these be behind a prefix? - Casey, Sun Dec 01 2024
    "p 1" '((lambda () (interactive) (tab-select 1)) :which-key "Tab 1")
    "p 2" '((lambda () (interactive) (tab-select 2)) :which-key "Tab 2")
    "p 3" '((lambda () (interactive) (tab-select 3)) :which-key "Tab 3")
    "p 4" '((lambda () (interactive) (tab-select 4)) :which-key "Tab 4")
    "p 5" '((lambda () (interactive) (tab-select 5)) :which-key "Tab 5")
    "p 6" '((lambda () (interactive) (tab-select 6)) :which-key "Tab 6")
    "p 7" '((lambda () (interactive) (tab-select 7)) :which-key "Tab 7")
    "p 8" '((lambda () (interactive) (tab-select 8)) :which-key "Tab 8")
    "p 9" '((lambda () (interactive) (tab-select 9)) :which-key "Tab 9")

    "p m"  '(:ignore m :which-key "Move Tab")
    "p m 1" '((lambda () (interactive) (tab-move-to 1)) :which-key "Move To Tab 1")
    "p m 2" '((lambda () (interactive) (tab-move-to 2)) :which-key "Move To Tab 2")
    "p m 3" '((lambda () (interactive) (tab-move-to 3)) :which-key "Move To Tab 3")
    "p m 4" '((lambda () (interactive) (tab-move-to 4)) :which-key "Move To Tab 4")
    "p m 5" '((lambda () (interactive) (tab-move-to 5)) :which-key "Move To Tab 5")
    "p m 6" '((lambda () (interactive) (tab-move-to 6)) :which-key "Move To Tab 6")
    "p m 7" '((lambda () (interactive) (tab-move-to 7)) :which-key "Move To Tab 7")
    "p m 8" '((lambda () (interactive) (tab-move-to 8)) :which-key "Move To Tab 8")
    "p m 9" '((lambda () (interactive) (tab-move-to 9)) :which-key "Move To Tab 9")

    "p d" '(project-dired :which-key "Directory")
    "p f" '(project-find-file :which-key "Find File")

    "p c" '(tabspaces-close-workspace :which-key "Close Project")
    "p k" '(tabspaces-kill-buffers-close-workspace :which-key "Close Project & Kill Buffers")

    "p n" '(tab-next :which-key "Next Project")
    "p p" '(tabspaces-open-or-create-project-and-workspace :which-key "Switch Project")
    "p t" '(custom/vterm-toggle-project :which-key "Terminal")

    "q"  '(:ignore q :which-key "quit/session")
    "q q" '(save-buffers-kill-terminal :which-key "Save and Close Emacs")
    ))

#+end_src

** Modular editing (evil)

#+begin_src emacs-lisp

  (use-package evil
    :ensure t
    ;; ## For some reason this is causing Evil mode to not work when I open a file - Casey, Fri Nov 29 2024
    ;; :bind
    ;; (:map vertico-map
    ;;   ("C-j" . vertico-next)
    ;;   ("C-k" . vertico-previous))
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    ;; ## Remove if you get `:bind` to work above - Casey, Fri Nov 29 2024
    (keymap-set vertico-map "C-j" 'vertico-next)
    (keymap-set vertico-map "C-k" 'vertico-previous)

    (keymap-set evil-insert-state-map "C-g" 'evil-normal-state)
    (keymap-set evil-insert-state-map "C-j" 'evil-next-line)
    (keymap-set evil-insert-state-map "C-k" 'evil-previous-line)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
    ;; ## Consider (setq evil-respect-visual-line-mode t) - Casey, Thu Nov 21 2024

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (evil-collection-init))

  (use-package evil-escape
    :ensure t
    :after evil
    :config
    (evil-escape-mode)
    (setq-default evil-escape-key-sequence "jk"))

#+end_src

** Dired

#+begin_src emacs-lisp

(use-package dired
  :after evil
  :config
  (setq dired-kill-when-opening-new-dired-buffer t)
  (evil-define-key 'normal dired-mode-map
    (kbd "h") 'dired-up-directory
    (kbd "l") 'dired-find-file
    )
  )

#+end_src

* Text Editing

** Spell Checking (Flyspell)

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package flyspell
  :hook ((org-mode git-commit-mode markdown-mode) . flyspell-mode)

  :config
  (setq flyspell-issue-message-flag nil
        flyspell-issue-welcome-flag nil))

#+end_src

** Editing Search Results (wgrep)

#+begin_src emacs-lisp

(use-package wgrep
  :ensure t
  :config
  (setq wgrep-auto-save-buffer t))

#+end_src

* Projects

** Tree Viewer (Treemacs)

#+begin_src emacs-lisp

(use-package treemacs
  :ensure t
  :bind ("s-b" . #'treemacs)
  :config
  (treemacs-follow-mode))

#+end_src

** Workspaces (Tabspaces)

#+begin_src emacs-lisp

(use-package tabspaces
  :ensure t
  :after consult

  :init
  (setq tabspaces-session-file (no-littering-expand-var-file-name "tabsession.el")
        tabspaces-project-switch-commands #'project-find-file)

  (tabspaces-mode)
  (global-tab-line-mode 1)

  :config
  (consult-customize consult--source-buffer :hidden t :default nil)
  ;; set consult-workspace buffer list
  (defvar consult--source-workspace
    (list :name "Workspace Buffers"
          :narrow ?w
          :history 'buffer-name-history
          :category 'buffer
          :state #'consult--buffer-state
          :default t
          :items (lambda () (consult--buffer-query
                             :predicate #'tabspaces--local-buffer-p
                             :sort 'visibility
                             :as #'buffer-name)))

    "Set workspace buffer list for consult-buffer.")
  (add-to-list 'consult-buffer-sources 'consult--source-workspace))

#+end_src

** Running tests

You can call ==vterm-send-string== when the current buffer is in ==vterm-mode== to automate populating the terminal prompt. After you can call ==vterm-send-return== to execute the prompt.

#+begin_src emacs-lisp

  (defun custom/test-component-project ()
    (interactive)
    (if (equal current-prefix-arg nil)
        (custom/split-with-process "ct")
        (custom/split-with-process "s && ct")
      ))

  (defun custom/test-web-project ()
    (interactive)
    (if (equal current-prefix-arg nil)
        (custom/split-with-process "rs")
        (custom/split-with-process "s && rs")
      ))

  (defun custom/split-with-process (command)
    (tab-bar-new-tab)
    (let ((test-buffer (generate-new-buffer "*testing*"))
          (process-buffer (generate-new-buffer "*process*")))
      (switch-to-buffer process-buffer)
      (vterm-mode)
      (vterm-send-string command)
      (vterm-send-return)
      (split-window-right)
      (switch-to-buffer test-buffer)
      (vterm-mode)
      ))

#+end_src

* File Types

** Defaults

*** Indentation

Two space indentation by default.

#+begin_src emacs-lisp

(setq-default indent-tabs-mode nil
              tab-width 2
              smie-indent-basic 2)

#+end_src

** Shell

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package shell
  :config
  (setq sh-basic-offset 2))

#+end_src

** Markdown

#+begin_src emacs-lisp

(use-package markdown-mode
  :ensure t
  :config
  (add-hook 'markdown-mode-hook #'visual-line-mode)
  (add-hook 'markdown-mode-hook #'visual-wrap-prefix-mode)

  (setq markdown-list-indent-width 2))

#+end_src

** Ruby

NOTE: Change the ==use-package== below to ==use-feature== if package management section above is enabled

#+begin_src emacs-lisp

(use-package ruby-mode
  :hook (ruby-mode . corfu-mode)
  ;; ## Enable this if Ripgrep capf is enabled above - Casey, Wed Nov 27 2024
  ;; :capf capf-dabbrev-ripgrep
  :config
  (setq ruby-block-indent nil
        ruby-method-call-indent nil
        ruby-method-params-indent nil
        ruby-after-operator-indent nil
        ruby-bracketed-args-indent nil))

#+end_src

** Haskell

#+begin_src emacs-lisp
(use-package haskell-mode
  :ensure t)
#+end_src

** YAML

#+begin_src emacs-lisp
(use-package yaml-mode
  :ensure t)
#+end_src

* Programming

** Go To Definition (Dumb Jump)

#+begin_src emacs-lisp

(use-package dumb-jump
  :ensure t
  :init
  (add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
  (setq xref-show-definitions-function #'xref-show-definitions-completing-read)

  (setq dumb-jump-force-searcher 'rg))

#+end_src

** Inserting Time

#+begin_src emacs-lisp

(defun custom/insert-date-time ()
  (interactive)
  ;; ## Enable once `evil-mode` is installed - Casey, Wed Nov 27 2024
  ;; (evil-append 0)
  (insert (format-time-string "%a %b %d %Y")))

#+end_src

** Comments

#+begin_src emacs-lisp

(defun custom/author ()
  (let ((env-author (getenv "AUTHOR")))
    (if env-author
        env-author
      "custom")
    ))

(defun custom/comment-attribution ()
  (interactive)
  ;; ## Enable once `evil-mode` is installed - Casey, Wed Nov 27 2024
  ;; (evil-append 0)
  (insert " - " (custom/author) ", ")
  (custom/insert-date-time))

#+end_src

* Version Control

** Magit

#+begin_src emacs-lisp

(use-package transient
  :ensure t)

(use-package magit
  :ensure t
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

#+end_src

* Terminal

** Terminal Emulator (vterm)

For some reason I have to do a ==elpaca rebuild== then select ==vterm== and close and reopen Emacs for it to compile and load ==vterm==.
After that Emacs loads without any warnings and ==vterm== works.

#+begin_src emacs-lisp

(use-package vterm
  :ensure (:wait t)
  :init
  (setq vterm-always-compile-module t
        ;; Defaults to 0.1. Decreasing this greatly impacts performance of
        ;; rendering large batches of text.
        vterm-timer-delay 0.06))

#+end_src

*** Toggle

#+begin_src emacs-lisp

(use-package vterm-toggle
  :ensure t
  :after vterm)

(defun custom/vterm-toggle-project ()
  (interactive)
  (let ((vterm-toggle-scope 'project))
    (vterm-toggle))
  )

#+end_src

* Ogranization

** Org mode

Currently unclear how I want to setup org mode, more research is needed

#+begin_src emacs-lisp :tangle no

(use-package org-mode)

#+end_src

* Presentations

** Org Reveal

#+begin_src emacs-lisp

(use-package ox-reveal
  :ensure t)

#+end_src

* Startup Time

Aaron had it setup to print out the start up time. I realize now that is a very
important thing to keep an eye on, but I usually leave Emacs open for extended
periods of time and don't close it often. Mostly leaving this a reminder to be
efficient in my configuration and always consider trade offs and decisions
rather than blowing past them.

Changed this from using a web hook:

#+begin_src emacs-lisp :tangle no

(add-hook 'after-init-hook
          (lambda ()
            (let ((inhibit-message t))
              (message "Emacs init time: %s" (emacs-init-time)))))

#+end_src

to setting the function =startup-echo-area-message= as that is the message that
Emacs will show at the bottom of the screen at startup and the default one is
very difficult to ignore

#+begin_src emacs-lisp

(defun startup-echo-area-message ()
  (format "Emacs init time: %s" (emacs-init-time)))

#+end_src
