#+TITLE: My GNU Emacs Config
#+AUTHOR: Me
#+DESCRIPTION: My personal Emacs config.
#+STARTUP: showeverything
#+OPTIONS: toc:3
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* TABLE OF CONTENTS :toc:
- [[#resources][Resources]]
- [[#load-first][LOAD FIRST]]
  - [[#automatic-package-updates][Automatic Package Updates]]
- [[#keep-folders-clean][Keep Folders Clean]]
- [[#basic-ui-configuration][Basic UI Configuration]]
- [[#keybinding-configuration][Keybinding Configuration]]
  - [[#dired][Dired]]
- [[#ui-configuration][UI Configuration]]
  - [[#color-theme][Color Theme]]
  - [[#better-modeline][Better Modeline]]
  - [[#which-key][Which Key]]
  - [[#ivy-and-counsel][Ivy and Counsel]]
  - [[#helpful-help-commands][Helpful Help Commands]]
  - [[#text-scaling][Text Scaling]]
  - [[#window-numbering][Window Numbering]]
  - [[#quick-switching-setups][Quick Switching Setups]]
- [[#projectile][Projectile]]
  - [[#path][Path]]
  - [[#search-all-projects][Search all projects]]
- [[#magit][Magit]]
- [[#workspaces][Workspaces]]
  - [[#perspective][Perspective]]
  - [[#perspective-projectile][Perspective Projectile]]
  - [[#perspective-tabs][Perspective Tabs]]
  - [[#tab-selection][Tab Selection]]
  - [[#tab-renaming][Tab Renaming]]
- [[#org-mode][Org Mode]]
  - [[#environment][Environment]]
  - [[#beginning][Beginning]]
  - [[#capture-templates][Capture Templates]]
  - [[#end][End]]
- [[#ztree][ZTree]]
- [[#github-browse-file][GitHub Browse File]]
- [[#envrc][Envrc]]
- [[#ripgrep][RipGrep]]
- [[#typescript-mode][TypeScript Mode]]
- [[#move-dup][Move Dup]]
- [[#vterm][vterm]]
- [[#markdown][Markdown]]
- [[#ruby][Ruby]]
  - [[#ruby-mode][Ruby Mode]]
  - [[#evil-ruby-text-object][Evil Ruby Text Object]]
- [[#whitespace][Whitespace]]
  - [[#whitespace-mode][Whitespace mode]]
- [[#time][Time]]
- [[#comments][Comments]]
- [[#multiple-cursors][Multiple Cursors]]
  - [[#highlight-select][Highlight select]]
  - [[#cursor-on-next-line][Cursor on next line]]
  - [[#end-1][End]]
- [[#movement][Movement]]

* Resources

Emacs from Scratch: https://github.com/daviwil/emacs-from-scratch/blob/master/Emacs.org?plain=1
Configuring Emacs: https://gitlab.com/dwt1/configuring-emacs/-/blob/main/06-cleaning-up-the-config/config.org?ref_type=heads&plain=1

* LOAD FIRST

#+begin_src emacs-lisp

  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

** Automatic Package Updates

The auto-package-update package helps us keep our Emacs packages up to date!  It will prompt you after a certain number of days either at startup or at a specific time of day to remind you to update your packages.

You can also use =M-x auto-package-update-now= to update right now!

#+begin_src emacs-lisp

  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))

#+end_src

* Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  ;(setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

* Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Disable line numbers for some modes
  (dolist (mode '(term-mode-hook
                  shell-mode-hook
                  vterm-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

* Keybinding Configuration

This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
    :after evil
    :config
    (general-create-definer custom/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")

    (custom/leader-keys
      "t"  '(:ignore t :which-key "toggles")

      "o ec" '(lambda () (interactive) (find-file (expand-file-name "~/.config/emacs/config.org")))

      "p"  '(:ignore p :which-key "project")
      "pp" '(projectile-persp-switch-project :which-key "Switch Project")
      "pk" '(perspective-tabs-close-tab :which-key "Close Project")

      "q"  '(:ignore q :which-key "quit/session")
      "qq" '(save-buffers-kill-terminal :which-key "Save and Close Emacs")
      )
    )

  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (keymap-set evil-insert-state-map "C-g" 'evil-normal-state)
    (keymap-set evil-insert-state-map "C-j" 'evil-next-line)
    (keymap-set evil-insert-state-map "C-k" 'evil-previous-line)

    ;; (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal)
    )

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init)
    )

  (use-package evil-escape
    :after evil
    :config
    (evil-escape-mode)
    (setq-default evil-escape-key-sequence "jk")
    )

#+end_src

** Dired

#+begin_src emacs-lisp

 (evil-define-key 'normal dired-mode-map
   (kbd "h") 'dired-up-directory
   (kbd "l") 'dired-find-file
   )

#+end_src

*** Hide Details

#+begin_src emacs-lisp

(add-hook 'dired-mode-hook
  (lambda ()
    (dired-hide-details-mode)
    ;; (dired-sort-toggle-or-edit)
    )
  )

#+end_src

* UI Configuration

** Color Theme

Modus themes are great for high contrast for easy visibility

#+begin_src emacs-lisp

  (use-package modus-themes
    :init (load-theme 'modus-operandi t))

#+end_src

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

(use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))

  (use-package counsel
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src

*** Improved Candidate Sorting with prescient.el

prescient.el provides some helpful behavior for sorting Ivy completion candidates based on how recently or frequently you select them.  This can be especially helpful when using =M-x= to run commands that you don't have bound to a key but still need to access occasionally.

This Prescient configuration is optimized for use in System Crafters videos and streams, check out the [[https://youtu.be/T9kygXveEz0][video on prescient.el]] for more details on how to configure it!

#+begin_src emacs-lisp

  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Uncomment the following line to have sorting remembered across sessions!
    ;(prescient-persist-mode 1)
    (ivy-prescient-mode 1))

#+end_src

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Text Scaling

This is an example of using [[https://github.com/abo-abo/hydra][Hydra]] to design a transient key binding for quickly adjusting the scale of the text on screen.  We define a hydra that is bound to =C-s t s= and, once activated, =j= and =k= increase and decrease the text scale.  You can press any other key (or =f= specifically) to exit the transient key map.

#+begin_src emacs-lisp

  (use-package hydra
    :defer t)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (custom/leader-keys
    "t s" '(hydra-text-scale/body :which-key "scale text"))

#+end_src

** Window Numbering

#+begin_src emacs-lisp

(use-package window-numbering
  :config
  (window-numbering-mode 1)
  )

#+end_src

** Quick Switching Setups
*** Sharing Setup

 When sharing with others the font size should be larger so its easier for them to read. When I'm solo I don't mind having the font be a bit smaller

#+begin_src emacs-lisp
(defun custom/set-sharing ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 185)

  ;; Setup magit to hide confusing data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header))

  ;; Set line numbering to be "normal"
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

#+end_src

*** Solo Setup

#+begin_src emacs-lisp

(defun custom/set-solo ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 150)

  ;; Setup magit status to have more data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header))

  ;; Set line numbering to be relative
  (setq display-line-numbers-type 'relative)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

#+end_src

*** Set Default Setup (Solo)

#+begin_src emacs-lisp

(custom/set-solo)

#+end_src

* Projectile

#+begin_src emacs-lisp

(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :custom ((projectile-completion-system 'ivy))
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  ;; ;; NOTE: Set this to the folder where you keep your Git repos!
  ;; (when (file-directory-p "~/Projects/Code")
  ;;   (setq projectile-project-search-path '("~/Projects/Code")))
  (setq projectile-switch-project-action #'projectile-dired))

(use-package counsel-projectile
  :config (counsel-projectile-mode))

#+end_src

** Path

#+begin_src emacs-lisp

(defun custom/projects-path ()
  (getenv "PROJECTS_PATH")
  )

(defun custom/set-projectile-project-path ()
  (interactive)
  (let ((projects-path (custom/projects-path))
        )
    (when projects-path
      (setq projectile-project-search-path (split-string projects-path))
      )
    )
  )

(custom/set-projectile-project-path)

#+end_src

** Search all projects

#+begin_src emacs-lisp

(defun custom/search-projects ()
  (interactive)
  (let ((default-directory (nth 0 (split-string (custom/projects-path))))
         )
    (call-interactively 'ripgrep-regexp)
    )
  )

(custom/leader-keys
  "s"  '(:ignore s :which-key "search")
  "s P" '(custom/search-projects :which-key "Search Projects"))

#+end_src

* Magit

#+begin_src emacs-lisp

(use-package magit
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
  )

#+end_src

* Workspaces

** Perspective
See the [README.md](https://github.com/nex3/perspective-el)

#+begin_src emacs-lisp

  (use-package perspective
    ;; :bind
    ;; ("C-x C-b" . persp-list-buffers)
    :custom
    ;; (persp-mode-prefix-key (kbd "C-c M-p"))  ; pick your own prefix key here
    (persp-suppress-no-prefix-key-warning t)
    :init
    (persp-mode)
    )

#+end_src

** Perspective Projectile

#+begin_src emacs-lisp

  (use-package persp-projectile
    :after perspective
    )

#+end_src

** Perspective Tabs
Taken from [this git repository](https://git.sr.ht/~woozong/perspective-tabs)


#+begin_src emacs-lisp

  (use-package perspective-tabs
    :load-path "manual"
    :after perspective
    :config
    (perspective-tabs-mode +1)
    )

#+end_src

** Tab Selection
See [Tab Bars](https://www.gnu.org/software/emacs/manual/html_node/emacs/Tab-Bars.html)

#+begin_src emacs-lisp

  (setq tab-bar-tab-hints t)
  (keymap-set evil-normal-state-map "C-M-1" '(lambda () (interactive) (tab-select 1)))
  (keymap-set evil-normal-state-map "C-M-2" '(lambda () (interactive) (tab-select 2)))
  (keymap-set evil-normal-state-map "C-M-3" '(lambda () (interactive) (tab-select 3)))
  (keymap-set evil-normal-state-map "C-M-4" '(lambda () (interactive) (tab-select 4)))
  (keymap-set evil-normal-state-map "C-M-5" '(lambda () (interactive) (tab-select 5)))
  (keymap-set evil-normal-state-map "C-M-6" '(lambda () (interactive) (tab-select 6)))
  (keymap-set evil-normal-state-map "C-M-7" '(lambda () (interactive) (tab-select 7)))
  (keymap-set evil-normal-state-map "C-M-8" '(lambda () (interactive) (tab-select 8)))
  (keymap-set evil-normal-state-map "C-M-9" '(lambda () (interactive) (tab-select 9)))

#+end_src

** Tab Renaming
[Reddit comment](https://www.reddit.com/r/emacs/comments/r16adq/comment/hlxl1ek/)

#+begin_src emacs-lisp

  ;; (use-package tab-bar
  ;;   :bind (:map tab-prefix-map ("p" . my/new-project-tab))
  ;;   :init
  ;;   (defun my/new-project-tab ()
  ;;     (interactive)
  ;;     (other-tab-prefix)
  ;;     (projectile-switch-project)
  ;;     (tab-rename (projectile-project-name))
  ;;     )
  ;;   )

#+end_src

* Org Mode

** Environment


#+begin_src emacs-lisp

(defun custom/org-files-path ()
  (or
   (getenv "ORG_FILES_PATH")
   "~/org-files"
   )
  )

(setq org-directory (custom/org-files-path))

#+end_src

** Beginning

#+begin_src emacs-lisp

  (use-package org
    ;; :hook (org-mode . efs/org-mode-setup)
    :config

#+end_src

** Capture Templates

#+begin_src emacs-lisp

    (setq org-capture-templates
      `(("t" "Tasks / Projects")
        ("tt" "Task" entry (file+olp "tasks.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

        ;; ("j" "Journal Entries")
        ;; ("jj" "Journal" entry
        ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
        ;;      "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
        ;;      ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
        ;;      :clock-in :clock-resume
        ;;      :empty-lines 1)
        ;; ("jm" "Meeting" entry
        ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
        ;;      "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
        ;;      :clock-in :clock-resume
        ;;      :empty-lines 1)

        ;; ("w" "Workflows")
        ;; ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
        ;;      "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

        ;; ("m" "Metrics Capture")
        ;; ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
        ;;  "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)
        )
      )

      ;; ## Not sure about this leader key set, need to think about it - Casey, Mon Apr 15 2024
      (custom/leader-keys
        "n"  '(:ignore n :which-key "note")
        "n t" '((lambda () (interactive) (org-capture nil "tt")) :which-key "Task Inbox")
        )

#+end_src

** End

#+begin_src emacs-lisp

  )

#+end_src

* ZTree

#+begin_src emacs-lisp

(use-package ztree
  )

#+end_src

* GitHub Browse File

#+begin_src emacs-lisp

(use-package github-browse-file
  )

#+end_src

* Envrc

#+begin_src emacs-lisp

(use-package envrc
  )

#+end_src

* RipGrep

#+begin_src emacs-lisp

(use-package ripgrep
  )

#+end_src

* TypeScript Mode

#+begin_src emacs-lisp

(use-package typescript-mode
  )

#+end_src

* Move Dup

#+begin_src emacs-lisp

(use-package move-dup
  )

#+end_src

* vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use =vterm= because there is a module that will need to be compiled before you can use it successfully.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    ;;(setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

#+end_src

* Markdown

#+begin_src emacs-lisp

  (use-package markdown-mode
    ;; :mode ("README\\.md\\'" . gfm-mode)
    ;; :init (setq markdown-command "multimarkdown")
    )

#+end_src

* Ruby

** Ruby Mode

#+begin_src emacs-lisp

(use-package ruby-mode
  )

#+end_src

** Evil Ruby Text Object

#+begin_src emacs-lisp

(use-package evil-ruby-text-objects
  :after ruby-mode
  :hook ruby-mode
  )

#+end_src

* Whitespace

** Whitespace mode

#+begin_src emacs-lisp

(global-whitespace-mode +1)
(setq whitespace-style '(face indentation trailing))

#+end_src

*** Trim lines with only spaces from a file

#+begin_src emacs-lisp

(defun custom/remove-space-lines ()
  (interactive)
  (evil-ex "%s/^ +$//")
  )

#+end_src

* Time

#+begin_src emacs-lisp

(defun custom/append-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string "%a %b %d %Y")))

(custom/leader-keys
  "d" '(custom/append-date-time :which-key "insert current time"))

(defun custom/insert-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string "%a %b %d %Y")))

#+end_src

* Comments

#+begin_src emacs-lisp

(defun custom/author ()
  (let ((env-author (getenv "AUTHOR")))
    (if env-author
        env-author
        "custom")
    )
  )
(defun custom/comment-attribution ()
  (interactive)
  (evil-append 0)
  (insert " - " (custom/author) ", ")
  (custom/insert-date-time)
  )

(custom/leader-keys
  "c"  '(:ignore c :which-key "comment")
  "c a" '(custom/comment-attribution :which-key "attribute comment"))

#+end_src

* Multiple Cursors

#+begin_src emacs-lisp

(use-package evil-mc
  :config
  (global-evil-mc-mode  1)

#+end_src

** Highlight select

I want to be able to quickly highlight only a select few matches and "g z d" is just too time consuming

#+begin_src emacs-lisp

  (keymap-set evil-insert-state-map "M-I" 'evil-mc-make-and-goto-next-match)
  (keymap-set evil-normal-state-map "M-I" 'evil-mc-make-and-goto-next-match)

#+end_src

** Cursor on next line

I want to be able to quickly add cursors below my current one if the changes lines up perfectly

#+begin_src emacs-lisp

  (keymap-set evil-insert-state-map "M-i" 'evil-mc-make-cursor-move-next-line)
  (keymap-set evil-normal-state-map "M-i" 'evil-mc-make-cursor-move-next-line)

#+end_src

** End

#+begin_src emacs-lisp

  )

#+end_src

* Movement
# ** Searching

# Search with swiper in buffer
# #+begin_src emacs-lisp
#
# (map! :desc "Search with Swiper" :n "C-s" #'+default/search-buffer)
# (map! :desc "Search with Swiper" :i "C-s" #'+default/search-buffer)
#
# #+end_src

# ** Workspaces

# *** Don't open one when switching projects

# #+begin_src emacs-lisp
#
# ;; (setq +workspaces-on-switch-project-behavior nil)
#
# #+end_src


